### ISSUE TITLE
Undefined array key "no_limits_value"

### ISSUE THREAD

**Issue by szabeszg** [teppokoivula/ListerCalculator#2]
Hello Teppo,

I still get this sometimes:
PHP Warning: Undefined array key "no_limits_value" in .../site/modules/ListerCalculator/ListerCalculator.module.php:180

**Comment by teppokoivula** [comment]
Hey @szabeszg,

Sorry, this should be fixed now in version 0.0.6 :)

**Comment by szabeszg** [comment]
Thanks! Looks like your fix solved the issue as I get no more warnings.
